---
#install aws collection
# - name: install ansible collections
#   include_role:
#     name: common
#     tasks_from: collections

#docker login
- name: docker login
  include_role:
    name: common
    tasks_from: ecr-login
  vars:
    ansible_python_interpreter: /usr/bin/python3
    region: us-east-1

- name: deploy ecs
  include_role:
    name: common
    tasks_from: ecs
  vars:
    container_name: "{{ frontend_container_name }}"
    image_version: "{{ frontend_image_version }}"
    container_image_url: "{{ frontend_container_image_url }}"
    container_port: "{{ frontend_container_port }}"
    container_memory: "{{ frontend_container_memory }}"
    container_cpu: "{{  frontend_container_cpu  }}"
    ecs_cluster_name: "{{frontend_ecs_cluster_name}}"
    execution_role: "{{frontend_task_execution_role}}"
    task_role: "{{frontend_task_role}}"
    sumo_collector_endpoint: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.sumo_collector_endpoint', nested=true, region='us-east-1' ) }}"
    sumo_collector_token: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.sumo_collector_token_frontend', nested=true, region='us-east-1' ) }}"    
    container_env:
      - name: REACT_APP_BACKEND_API
        value: "{% if tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/v1/graphql/{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/v1/graphql/{% endif %}"
      - name: REACT_APP_FILE_SERVICE_API
        value: "{% if tier == 'prod' %}https://{{subdomain}}.{{domain_name}}/api/files/{% else %}https://{{subdomain}}-{{tier}}.{{domain_name}}/api/files/{% endif %}"
      # - name: REACT_APP_BE_VERSION
      #   value: "{{ backend_version }}"
      - name: REACT_APP_FE_VERSION
        value: "{{frontend_version}}"
      - name: REACT_APP_ABOUT_CONTENT_URL
        value: "{{about_content_url}}"
      - name: NEW_RELIC_LICENSE_KEY
        value: "{{ newrelic_license_key }}"
      - name: NEW_RELIC_APP_NAME
        value: "{{ app_name }}-{{container_name}}"
      - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
        value: "true"
      - name: NEW_RELIC_HOST
        value: "gov-collector.newrelic.com"
      - name: NEW_RELIC_NO_CONFIG_FILE
        value: "true"
      - name: NEW_RELIC_LABELS
        value: "Project:{{ project_name }};Environment:{{ tier }}"
      - name: REACT_APP_GOOGLE_CLIENT_ID
        value: "196014713877-0d926jpdd691roubuc0kpu6r6ha9b9t5.apps.googleusercontent.com"