- name: hub frontend pipeline
  hosts: hub
  connection: local
  gather_facts: no
  become: no
  remote_user: ccdi-docker

  tasks:
    - name: build stage for hub frontend
      include_role:
        name: bento-hub
        tasks_from: deploy-frontend
      vars:
        ansible_python_interpreter: /usr/bin/python3