- name: OpenSearch restore for HUB
  hosts: hub
  connection: local
  gather_facts: no
  become: no
  remote_user: ccdi-docker
    
  tasks:
    - name: elasticsearch data restore
      include_role:
        name: hub-dataloading
        tasks_from: opensearchrestore
      vars:
        ansible_python_interpreter: /bin/python3