---
- name: load data to neo4j db
  hosts: loader
  connection: local
  gather_facts: yes
  #become: yes

  tasks:
    #install collections
    # - name: install aws collection
    #   shell: "ansible-galaxy collection install {{ item | quote }} --force"
    #   loop:
    #     - community.aws:<=3.2.0
    #     - git+https://github.com/CBIIT/datacommons-devops.git#/ansible/collections/bento/common/,v1.5
    #   vars:
    #     ansible_python_interpreter: /usr/bin/python3

    # DEBUG
    - name: print load_mode
      command: echo "{{ lookup('env','LOAD_MODE') }}"
      register: load_mode_var

    - name: print load_mode
      debug: msg="{{ load_mode_var.stdout }}"
    
    #load data
    - name: perform data loading
      include_role:
        name: bento.common.data_loader
      vars:
        ansible_python_interpreter: /usr/bin/python3
        workspace: "{{ lookup('env','WORKSPACE') }}"
        project_name:  "{{ lookup('env','PROJECT_NAME') }}"
        tier: "{{ lookup('env','TIER') }}"
        data_bucket: "{{ lookup('env','S3_BUCKET') }}"
        s3_folder: "{{ lookup('env','S3_FOLDER') }}"
        wipe_db:  "{{ lookup('env','WIPE_DB') }}"
        load_mode:  "{{ lookup('env','LOAD_MODE') }}"
        cheat_mode:  "{{ lookup('env','CHEAT_MODE')}}"
        split_transactions:  "{{ lookup('env','SPLIT')}}"
        region: us-east-1
        neo4j_user: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.neo4j_user', nested=true, region='us-east-1' ) }}"
        neo4j_password: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.neo4j_password', nested=true, region='us-east-1' ) }}"
        neo4j_ip: "{{ lookup('amazon.aws.aws_secret', 'bento/{{ project_name }}/{{ tier }}.neo4j_ip', nested=true, region='us-east-1' ) }}"
        model_file1: "{{ workspace }}/ccdi-model/model-desc/ccdi-model.yml"
        model_file2: "{{ workspace }}/ccdi-model/model-desc/ccdi-model-props.yml"
        property_file: "config/props-ccdi-model.yml"